### ISSUE TITLE
Erro no download 

### ISSUE THREAD

**Issue by WellingtonMonteiro** [Dniel97/orpheusdl-bugsmusic#2]
____             _                    _____  _
  / __ \           | |                  |  __ \| |
 | |  | |_ __ _ __ | |__   ___ _   _ ___| |  | | |
 | |  | | '__| '_ \| '_ \ / _ \ | | / __| |  | | |
 | |__| | |  | |_) | | | |  __/ |_| \__ \ |__| | |____
  \____/|_|  | .__/|_| |_|\___|\__,_|___/_____/|______|
             | |
             |_|

=== Downloading album Sucessos - Eduardo Costa e Di Paullo & Paulino (12150459) ===
Artist: Di Paullo & Paulino (8100716)
Year: 2013
Number of tracks: 12
Service: Bugs
Downloading album cover

Track 1/12
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/orpheusdl/orpheus.py", line 223, in <module>
    main()
  File "/data/data/com.termux/files/home/orpheusdl/orpheus.py", line 218, in main
    orpheus_core_download(orpheus, media_to_download, tpm, sdm, path)
  File "/data/data/com.termux/files/home/orpheusdl/orpheus/core.py", line 389, in orpheus_core_download
    downloader.download_album(media_id, extra_kwargs=media.extra_kwargs)
  File "/data/data/com.termux/files/home/orpheusdl/orpheus/music_downloader.py", line 172, in download_album
    self.download_track(track_id, album_location=album_path, track_index=index, number_of_tracks=number_of_tracks, main_artist=artist_name, cover_temp_location=cover_temp_location, indent_level=indent_level+1, extra_kwargs=album_info.track_extra_kwargs)
  File "/data/data/com.termux/files/home/orpheusdl/orpheus/music_downloader.py", line 224, in download_track
    track_info: TrackInfo = self.service.get_track_info(track_id, quality_tier, codec_options, **extra_kwargs)
  File "/data/data/com.termux/files/home/orpheusdl/modules/orpheusdl-bugsmusic/interface.py", line 309, in get_track_info
    track_info = TrackInfo(
TypeError: TrackInfo.__init__() got an unexpected keyword argument 'duration'
~/orpheusdl $

**Comment by Dniel97** [comment]
If you update the module you also need to update OrpheusDL!
